# Generated by Django 3.2 on 2022-08-16 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_elect_shop_sh_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elect_shop',
            old_name='sh_name',
            new_name='shop_name',
        ),
    ]
