# Generated by Django 3.2 on 2022-08-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_sh_name_elect_shop_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elect_shop',
            name='item_no',
        ),
    ]
