# Generated by Django 3.2 on 2022-08-17 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_elect_shop_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elect_shop',
            name='shop_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
    ]
